/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Ajout (void)
{
  GtkWidget *Ajout;
  GtkWidget *fixed1;
  GtkWidget *EID;
  GtkWidget *ENOM;
  GtkObject *SBJJ_ajout_adj;
  GtkWidget *SBJJ_ajout;
  GtkObject *SBMM_ajout_adj;
  GtkWidget *SBMM_ajout;
  GtkObject *SBBLOC_ajout_adj;
  GtkWidget *SBBLOC_ajout;
  GtkWidget *ECAPACITE;
  GtkObject *SBYYYY_ajout_adj;
  GtkWidget *SBYYYY_ajout;
  GtkWidget *annuler;
  GtkWidget *image2;
  GtkWidget *ajouter_parking;
  GtkWidget *image1;
  GtkWidget *label99;
  GtkWidget *image30;
  GtkWidget *CBREGION_ajout;
  GtkWidget *label3;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label23;
  GtkWidget *label25;
  GtkWidget *RBSURFACE;
  GSList *RBSURFACE_group = NULL;
  GtkWidget *RBSOUSTERRAIN;
  GtkWidget *label49;
  GtkWidget *label4;
  GtkWidget *confirmation_fekher;
  GtkWidget *alignment20;
  GtkWidget *hbox19;
  GtkWidget *image34;
  GtkWidget *label109;
  GtkWidget *RBAERIEN;

  Ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajout), _("ajout"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Ajout), fixed1);

  EID = gtk_entry_new ();
  gtk_widget_show (EID);
  gtk_fixed_put (GTK_FIXED (fixed1), EID, 176, 104);
  gtk_widget_set_size_request (EID, 172, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (EID), 8226);

  ENOM = gtk_entry_new ();
  gtk_widget_show (ENOM);
  gtk_fixed_put (GTK_FIXED (fixed1), ENOM, 176, 152);
  gtk_widget_set_size_request (ENOM, 172, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (ENOM), 8226);

  SBJJ_ajout_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  SBJJ_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (SBJJ_ajout_adj), 1, 0);
  gtk_widget_show (SBJJ_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), SBJJ_ajout, 136, 464);
  gtk_widget_set_size_request (SBJJ_ajout, 50, 28);

  SBMM_ajout_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  SBMM_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (SBMM_ajout_adj), 1, 0);
  gtk_widget_show (SBMM_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), SBMM_ajout, 216, 464);
  gtk_widget_set_size_request (SBMM_ajout, 50, 28);

  SBBLOC_ajout_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  SBBLOC_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (SBBLOC_ajout_adj), 1, 0);
  gtk_widget_show (SBBLOC_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), SBBLOC_ajout, 176, 304);
  gtk_widget_set_size_request (SBBLOC_ajout, 50, 28);

  ECAPACITE = gtk_entry_new ();
  gtk_widget_show (ECAPACITE);
  gtk_fixed_put (GTK_FIXED (fixed1), ECAPACITE, 176, 256);
  gtk_widget_set_size_request (ECAPACITE, 172, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (ECAPACITE), 8226);

  SBYYYY_ajout_adj = gtk_adjustment_new (2024, 2024, 2060, 1, 10, 10);
  SBYYYY_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (SBYYYY_ajout_adj), 1, 0);
  gtk_widget_show (SBYYYY_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), SBYYYY_ajout, 288, 464);
  gtk_widget_set_size_request (SBYYYY_ajout, 70, 29);

  annuler = gtk_button_new ();
  gtk_widget_show (annuler);
  gtk_fixed_put (GTK_FIXED (fixed1), annuler, 288, 560);
  gtk_widget_set_size_request (annuler, 90, 50);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (annuler), image2);

  ajouter_parking = gtk_button_new ();
  gtk_widget_show (ajouter_parking);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter_parking, 104, 560);
  gtk_widget_set_size_request (ajouter_parking, 88, 50);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (ajouter_parking), image1);

  label99 = gtk_label_new_with_mnemonic (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Ajouter un parking  </span></u>"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed1), label99, 264, 16);
  gtk_widget_set_size_request (label99, 272, 56);
  gtk_label_set_use_markup (GTK_LABEL (label99), TRUE);

  image30 = create_pixmap (Ajout, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed1), image30, 408, 128);
  gtk_widget_set_size_request (image30, 352, 272);

  CBREGION_ajout = gtk_combo_box_new_text ();
  gtk_widget_show (CBREGION_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), CBREGION_ajout, 176, 200);
  gtk_widget_set_size_request (CBREGION_ajout, 240, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Centre_ville_Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Sidi_Bousaid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("El_Manzeh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Lac1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Lac2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Carthage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Centre_ville_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Zone_Indus_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Centre_Ville_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Zone_Indus_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Azur_City  "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Tunis_City "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Manar_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Tunisia_Mall "));

  label3 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Region de parking</span>"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 0, 200);
  gtk_widget_set_size_request (label3, 168, 32);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  label1 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Nom de parking</span>"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 24, 152);
  gtk_widget_set_size_request (label1, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  label2 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Id parking</span>"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 64, 104);
  gtk_widget_set_size_request (label2, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  label23 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Capacit\303\251</span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed1), label23, 56, 256);
  gtk_widget_set_size_request (label23, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label25 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Nombre de blocs</span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed1), label25, 8, 304);
  gtk_widget_set_size_request (label25, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  RBSURFACE = gtk_radio_button_new_with_mnemonic (NULL, _("sur surface"));
  gtk_widget_show (RBSURFACE);
  gtk_fixed_put (GTK_FIXED (fixed1), RBSURFACE, 176, 384);
  gtk_widget_set_size_request (RBSURFACE, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RBSURFACE), RBSURFACE_group);
  RBSURFACE_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RBSURFACE));

  RBSOUSTERRAIN = gtk_radio_button_new_with_mnemonic (NULL, _("sous-terrain"));
  gtk_widget_show (RBSOUSTERRAIN);
  gtk_fixed_put (GTK_FIXED (fixed1), RBSOUSTERRAIN, 176, 416);
  gtk_widget_set_size_request (RBSOUSTERRAIN, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RBSOUSTERRAIN), RBSURFACE_group);
  RBSURFACE_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RBSOUSTERRAIN));

  label49 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Type de parking</span>"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed1), label49, 8, 384);
  gtk_widget_set_size_request (label49, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  label4 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Date d'ajout</span>"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 0, 464);
  gtk_widget_set_size_request (label4, 128, 24);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  confirmation_fekher = gtk_check_button_new ();
  gtk_widget_show (confirmation_fekher);
  gtk_fixed_put (GTK_FIXED (fixed1), confirmation_fekher, 168, 504);
  gtk_widget_set_size_request (confirmation_fekher, 136, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (confirmation_fekher), alignment20);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox19);

  image34 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox19), image34, FALSE, FALSE, 0);

  label109 = gtk_label_new_with_mnemonic (_("Confirmation"));
  gtk_widget_show (label109);
  gtk_box_pack_start (GTK_BOX (hbox19), label109, FALSE, FALSE, 0);

  RBAERIEN = gtk_radio_button_new_with_mnemonic (NULL, _("a\303\251rien"));
  gtk_widget_show (RBAERIEN);
  gtk_fixed_put (GTK_FIXED (fixed1), RBAERIEN, 176, 352);
  gtk_widget_set_size_request (RBAERIEN, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RBAERIEN), RBSURFACE_group);
  RBSURFACE_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RBAERIEN));

  g_signal_connect ((gpointer) annuler, "clicked",
                    G_CALLBACK (on_annuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_parking, "clicked",
                    G_CALLBACK (on_ajouter_parking_clicked),
                    NULL);
  g_signal_connect ((gpointer) RBSURFACE, "toggled",
                    G_CALLBACK (on_RBSURFACE_toggled),
                    NULL);
  g_signal_connect ((gpointer) RBSOUSTERRAIN, "toggled",
                    G_CALLBACK (on_RBSOUSTERRAIN_toggled),
                    NULL);
  g_signal_connect ((gpointer) confirmation_fekher, "toggled",
                    G_CALLBACK (on_confirmation_fekher_toggled),
                    NULL);
  g_signal_connect ((gpointer) RBAERIEN, "toggled",
                    G_CALLBACK (on_RBAERIEN_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout, Ajout, "Ajout");
  GLADE_HOOKUP_OBJECT (Ajout, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Ajout, EID, "EID");
  GLADE_HOOKUP_OBJECT (Ajout, ENOM, "ENOM");
  GLADE_HOOKUP_OBJECT (Ajout, SBJJ_ajout, "SBJJ_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, SBMM_ajout, "SBMM_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, SBBLOC_ajout, "SBBLOC_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, ECAPACITE, "ECAPACITE");
  GLADE_HOOKUP_OBJECT (Ajout, SBYYYY_ajout, "SBYYYY_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, annuler, "annuler");
  GLADE_HOOKUP_OBJECT (Ajout, image2, "image2");
  GLADE_HOOKUP_OBJECT (Ajout, ajouter_parking, "ajouter_parking");
  GLADE_HOOKUP_OBJECT (Ajout, image1, "image1");
  GLADE_HOOKUP_OBJECT (Ajout, label99, "label99");
  GLADE_HOOKUP_OBJECT (Ajout, image30, "image30");
  GLADE_HOOKUP_OBJECT (Ajout, CBREGION_ajout, "CBREGION_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, label3, "label3");
  GLADE_HOOKUP_OBJECT (Ajout, label1, "label1");
  GLADE_HOOKUP_OBJECT (Ajout, label2, "label2");
  GLADE_HOOKUP_OBJECT (Ajout, label23, "label23");
  GLADE_HOOKUP_OBJECT (Ajout, label25, "label25");
  GLADE_HOOKUP_OBJECT (Ajout, RBSURFACE, "RBSURFACE");
  GLADE_HOOKUP_OBJECT (Ajout, RBSOUSTERRAIN, "RBSOUSTERRAIN");
  GLADE_HOOKUP_OBJECT (Ajout, label49, "label49");
  GLADE_HOOKUP_OBJECT (Ajout, label4, "label4");
  GLADE_HOOKUP_OBJECT (Ajout, confirmation_fekher, "confirmation_fekher");
  GLADE_HOOKUP_OBJECT (Ajout, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Ajout, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Ajout, image34, "image34");
  GLADE_HOOKUP_OBJECT (Ajout, label109, "label109");
  GLADE_HOOKUP_OBJECT (Ajout, RBAERIEN, "RBAERIEN");

  return Ajout;
}

GtkWidget*
create_affectation (void)
{
  GtkWidget *affectation;
  GtkWidget *fixed4;
  GtkWidget *label107;
  GtkWidget *return_affect;
  GtkWidget *alignment17;
  GtkWidget *hbox16;
  GtkWidget *image26;
  GtkWidget *label103;
  GtkWidget *treeview1;
  GtkWidget *image31;
  GtkWidget *label101;
  GtkWidget *entry_agent_affect;
  GtkWidget *annuler_affectation;
  GtkWidget *alignment18;
  GtkWidget *hbox17;
  GtkWidget *image27;
  GtkWidget *label104;
  GtkWidget *affectation_agent;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image10;
  GtkWidget *label12;

  affectation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affectation), _("affectation"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (affectation), fixed4);

  label107 = gtk_label_new_with_mnemonic (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Affectation d'un agent   </span></u>"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed4), label107, 176, 16);
  gtk_widget_set_size_request (label107, 328, 40);
  gtk_label_set_use_markup (GTK_LABEL (label107), TRUE);

  return_affect = gtk_button_new ();
  gtk_widget_show (return_affect);
  gtk_fixed_put (GTK_FIXED (fixed4), return_affect, 24, 16);
  gtk_widget_set_size_request (return_affect, 74, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (return_affect), alignment17);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox16);

  image26 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox16), image26, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("return"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox16), label103, FALSE, FALSE, 0);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview1, 80, 248);
  gtk_widget_set_size_request (treeview1, 616, 208);

  image31 = create_pixmap (affectation, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed4), image31, 528, 24);
  gtk_widget_set_size_request (image31, 256, 208);

  label101 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Selectionner un agent :</span>"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed4), label101, 32, 112);
  gtk_widget_set_size_request (label101, 200, 48);
  gtk_label_set_use_markup (GTK_LABEL (label101), TRUE);

  entry_agent_affect = gtk_entry_new ();
  gtk_widget_show (entry_agent_affect);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_agent_affect, 272, 120);
  gtk_widget_set_size_request (entry_agent_affect, 208, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_agent_affect), 8226);

  annuler_affectation = gtk_button_new ();
  gtk_widget_show (annuler_affectation);
  gtk_fixed_put (GTK_FIXED (fixed4), annuler_affectation, 512, 496);
  gtk_widget_set_size_request (annuler_affectation, 142, 41);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (annuler_affectation), alignment18);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox17);

  image27 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox17), image27, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox17), label104, FALSE, FALSE, 0);

  affectation_agent = gtk_button_new ();
  gtk_widget_show (affectation_agent);
  gtk_fixed_put (GTK_FIXED (fixed4), affectation_agent, 96, 496);
  gtk_widget_set_size_request (affectation_agent, 150, 41);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (affectation_agent), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox2), image10, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Affecter"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox2), label12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) return_affect, "clicked",
                    G_CALLBACK (on_return_affect_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) annuler_affectation, "clicked",
                    G_CALLBACK (on_annuler_affectation_clicked),
                    NULL);
  g_signal_connect ((gpointer) affectation_agent, "clicked",
                    G_CALLBACK (on_affectation_agent_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affectation, affectation, "affectation");
  GLADE_HOOKUP_OBJECT (affectation, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (affectation, label107, "label107");
  GLADE_HOOKUP_OBJECT (affectation, return_affect, "return_affect");
  GLADE_HOOKUP_OBJECT (affectation, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (affectation, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (affectation, image26, "image26");
  GLADE_HOOKUP_OBJECT (affectation, label103, "label103");
  GLADE_HOOKUP_OBJECT (affectation, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (affectation, image31, "image31");
  GLADE_HOOKUP_OBJECT (affectation, label101, "label101");
  GLADE_HOOKUP_OBJECT (affectation, entry_agent_affect, "entry_agent_affect");
  GLADE_HOOKUP_OBJECT (affectation, annuler_affectation, "annuler_affectation");
  GLADE_HOOKUP_OBJECT (affectation, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (affectation, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (affectation, image27, "image27");
  GLADE_HOOKUP_OBJECT (affectation, label104, "label104");
  GLADE_HOOKUP_OBJECT (affectation, affectation_agent, "affectation_agent");
  GLADE_HOOKUP_OBJECT (affectation, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (affectation, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (affectation, image10, "image10");
  GLADE_HOOKUP_OBJECT (affectation, label12, "label12");

  return affectation;
}

GtkWidget*
create_GestionParky (void)
{
  GtkWidget *GestionParky;
  GtkWidget *fixed5;
  GtkWidget *ERECHERCHE;
  GtkWidget *ENOM_m;
  GtkWidget *ECAPACITE_m;
  GtkObject *SBBLOC_m_adj;
  GtkWidget *SBBLOC_m;
  GtkObject *SBJJ_m_adj;
  GtkWidget *SBJJ_m;
  GtkObject *SBMM_m_adj;
  GtkWidget *SBMM_m;
  GtkObject *SBYYYY_m_adj;
  GtkWidget *SBYYYY_m;
  GtkWidget *modifier_fekher;
  GtkWidget *alignment16;
  GtkWidget *hbox15;
  GtkWidget *image25;
  GtkWidget *label57;
  GtkWidget *supprimer_fekher;
  GtkWidget *alignment8;
  GtkWidget *hbox7;
  GtkWidget *image16;
  GtkWidget *label36;
  GtkWidget *loop;
  GtkWidget *image15;
  GtkWidget *RBSOUSTERRAIN_m;
  GSList *RBSOUSTERRAIN_m_group = NULL;
  GtkWidget *RBSURFACE_m;
  GtkWidget *RBAERIEN_m;
  GtkWidget *CBREGION_m;
  GtkWidget *Ajouter_PARKY;
  GtkWidget *alignment12;
  GtkWidget *hbox11;
  GtkWidget *image20;
  GtkWidget *label41;
  GtkWidget *label38;
  GtkWidget *afficher_fekher;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image18;
  GtkWidget *label39;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_parking;
  GtkWidget *label42;
  GtkWidget *label55;
  GtkWidget *label54;
  GtkWidget *label53;
  GtkWidget *label52;
  GtkWidget *label51;
  GtkWidget *label56;
  GtkWidget *image32;
  GtkWidget *label43;
  GtkWidget *afficher_affect_agent;
  GtkWidget *alignment19;
  GtkWidget *hbox18;
  GtkWidget *image33;
  GtkWidget *label108;

  GestionParky = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GestionParky), _("gestions des Parking"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (GestionParky), fixed5);

  ERECHERCHE = gtk_entry_new ();
  gtk_widget_show (ERECHERCHE);
  gtk_fixed_put (GTK_FIXED (fixed5), ERECHERCHE, 832, 56);
  gtk_widget_set_size_request (ERECHERCHE, 208, 35);
  gtk_entry_set_text (GTK_ENTRY (ERECHERCHE), "Id ...");
  gtk_entry_set_invisible_char (GTK_ENTRY (ERECHERCHE), 46);

  ENOM_m = gtk_entry_new ();
  gtk_widget_show (ENOM_m);
  gtk_fixed_put (GTK_FIXED (fixed5), ENOM_m, 904, 224);
  gtk_widget_set_size_request (ENOM_m, 224, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (ENOM_m), 8226);

  ECAPACITE_m = gtk_entry_new ();
  gtk_widget_show (ECAPACITE_m);
  gtk_fixed_put (GTK_FIXED (fixed5), ECAPACITE_m, 904, 320);
  gtk_widget_set_size_request (ECAPACITE_m, 224, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (ECAPACITE_m), 8226);

  SBBLOC_m_adj = gtk_adjustment_new (1, 1, 10, 1, 10, 10);
  SBBLOC_m = gtk_spin_button_new (GTK_ADJUSTMENT (SBBLOC_m_adj), 1, 0);
  gtk_widget_show (SBBLOC_m);
  gtk_fixed_put (GTK_FIXED (fixed5), SBBLOC_m, 904, 368);
  gtk_widget_set_size_request (SBBLOC_m, 50, 28);

  SBJJ_m_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  SBJJ_m = gtk_spin_button_new (GTK_ADJUSTMENT (SBJJ_m_adj), 1, 0);
  gtk_widget_show (SBJJ_m);
  gtk_fixed_put (GTK_FIXED (fixed5), SBJJ_m, 888, 520);
  gtk_widget_set_size_request (SBJJ_m, 50, 28);

  SBMM_m_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  SBMM_m = gtk_spin_button_new (GTK_ADJUSTMENT (SBMM_m_adj), 1, 0);
  gtk_widget_show (SBMM_m);
  gtk_fixed_put (GTK_FIXED (fixed5), SBMM_m, 952, 520);
  gtk_widget_set_size_request (SBMM_m, 50, 28);

  SBYYYY_m_adj = gtk_adjustment_new (2024, 2024, 2060, 1, 10, 10);
  SBYYYY_m = gtk_spin_button_new (GTK_ADJUSTMENT (SBYYYY_m_adj), 1, 0);
  gtk_widget_show (SBYYYY_m);
  gtk_fixed_put (GTK_FIXED (fixed5), SBYYYY_m, 1016, 520);
  gtk_widget_set_size_request (SBYYYY_m, 70, 29);

  modifier_fekher = gtk_button_new ();
  gtk_widget_show (modifier_fekher);
  gtk_fixed_put (GTK_FIXED (fixed5), modifier_fekher, 888, 584);
  gtk_widget_set_size_request (modifier_fekher, 150, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (modifier_fekher), alignment16);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox15);

  image25 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox15), image25, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox15), label57, FALSE, FALSE, 0);

  supprimer_fekher = gtk_button_new ();
  gtk_widget_show (supprimer_fekher);
  gtk_fixed_put (GTK_FIXED (fixed5), supprimer_fekher, 240, 584);
  gtk_widget_set_size_request (supprimer_fekher, 150, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (supprimer_fekher), alignment8);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox7);

  image16 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox7), image16, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox7), label36, FALSE, FALSE, 0);

  loop = gtk_button_new ();
  gtk_widget_show (loop);
  gtk_fixed_put (GTK_FIXED (fixed5), loop, 1048, 56);
  gtk_widget_set_size_request (loop, 64, 37);

  image15 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_container_add (GTK_CONTAINER (loop), image15);

  RBSOUSTERRAIN_m = gtk_radio_button_new_with_mnemonic (NULL, _("Sous-Terrain"));
  gtk_widget_show (RBSOUSTERRAIN_m);
  gtk_fixed_put (GTK_FIXED (fixed5), RBSOUSTERRAIN_m, 920, 408);
  gtk_widget_set_size_request (RBSOUSTERRAIN_m, 144, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RBSOUSTERRAIN_m), RBSOUSTERRAIN_m_group);
  RBSOUSTERRAIN_m_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RBSOUSTERRAIN_m));

  RBSURFACE_m = gtk_radio_button_new_with_mnemonic (NULL, _("Surface"));
  gtk_widget_show (RBSURFACE_m);
  gtk_fixed_put (GTK_FIXED (fixed5), RBSURFACE_m, 920, 440);
  gtk_widget_set_size_request (RBSURFACE_m, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RBSURFACE_m), RBSOUSTERRAIN_m_group);
  RBSOUSTERRAIN_m_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RBSURFACE_m));

  RBAERIEN_m = gtk_radio_button_new_with_mnemonic (NULL, _("A\303\251rien"));
  gtk_widget_show (RBAERIEN_m);
  gtk_fixed_put (GTK_FIXED (fixed5), RBAERIEN_m, 920, 472);
  gtk_widget_set_size_request (RBAERIEN_m, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RBAERIEN_m), RBSOUSTERRAIN_m_group);
  RBSOUSTERRAIN_m_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RBAERIEN_m));

  CBREGION_m = gtk_combo_box_new_text ();
  gtk_widget_show (CBREGION_m);
  gtk_fixed_put (GTK_FIXED (fixed5), CBREGION_m, 904, 272);
  gtk_widget_set_size_request (CBREGION_m, 224, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Centre_ville_Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Sidi_Bousaid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("El_Manzeh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Lac1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Lac2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Carthage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Centre_ville_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Zone_Indus_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Centre_Ville_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Zone_Indus_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Azur_City  "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Tunis_City "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Manar_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Tunisia_Mall "));

  Ajouter_PARKY = gtk_button_new ();
  gtk_widget_show (Ajouter_PARKY);
  gtk_fixed_put (GTK_FIXED (fixed5), Ajouter_PARKY, 32, 584);
  gtk_widget_set_size_request (Ajouter_PARKY, 150, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (Ajouter_PARKY), alignment12);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox11);

  image20 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox11), image20, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox11), label41, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label41, 80, 30);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  label38 = gtk_label_new ("");
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 800, 592);
  gtk_widget_set_size_request (label38, 369, 41);

  afficher_fekher = gtk_button_new ();
  gtk_widget_show (afficher_fekher);
  gtk_fixed_put (GTK_FIXED (fixed5), afficher_fekher, 456, 584);
  gtk_widget_set_size_request (afficher_fekher, 150, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (afficher_fekher), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image18 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox9), image18, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox9), label39, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow1, 32, 240);
  gtk_widget_set_size_request (scrolledwindow1, 672, 304);

  treeview_parking = gtk_tree_view_new ();
  gtk_widget_show (treeview_parking);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_parking);
  gtk_widget_set_size_request (treeview_parking, 800, 300);

  label42 = gtk_label_new (_("<span color=\"navy Blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">Faire une Modification </span>"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed5), label42, 840, 152);
  gtk_widget_set_size_request (label42, 304, 48);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  label55 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Nom de parking</span>"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed5), label55, 752, 224);
  gtk_widget_set_size_request (label55, 160, 32);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  label54 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Region de parking</span>\n"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed5), label54, 744, 280);
  gtk_widget_set_size_request (label54, 160, 24);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  label53 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Capacit\303\251</span>\n"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed5), label53, 816, 328);
  gtk_widget_set_size_request (label53, 88, 16);
  gtk_label_set_use_markup (GTK_LABEL (label53), TRUE);

  label52 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Nombres de blocs</span>"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed5), label52, 736, 368);
  gtk_widget_set_size_request (label52, 168, 32);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  label51 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Type de parking</span>"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed5), label51, 752, 440);
  gtk_widget_set_size_request (label51, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  label56 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Date d'ajout</span>"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed5), label56, 760, 520);
  gtk_widget_set_size_request (label56, 128, 24);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  image32 = create_pixmap (GestionParky, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed5), image32, 576, 8);
  gtk_widget_set_size_request (image32, 248, 208);

  label43 = gtk_label_new (_("<span color=\"navy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">Listes des Parkings </span>"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed5), label43, 160, 160);
  gtk_widget_set_size_request (label43, 392, 56);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  afficher_affect_agent = gtk_button_new ();
  gtk_widget_show (afficher_affect_agent);
  gtk_fixed_put (GTK_FIXED (fixed5), afficher_affect_agent, 648, 584);
  gtk_widget_set_size_request (afficher_affect_agent, 136, 40);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (afficher_affect_agent), alignment19);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox18);

  image33 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox18), image33, FALSE, FALSE, 0);

  label108 = gtk_label_new_with_mnemonic (_("Affecter"));
  gtk_widget_show (label108);
  gtk_box_pack_start (GTK_BOX (hbox18), label108, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) modifier_fekher, "clicked",
                    G_CALLBACK (on_modifier_fekher_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_fekher, "clicked",
                    G_CALLBACK (on_supprimer_fekher_clicked),
                    NULL);
  g_signal_connect ((gpointer) loop, "clicked",
                    G_CALLBACK (on_loop_clicked),
                    NULL);
  g_signal_connect ((gpointer) RBSOUSTERRAIN_m, "toggled",
                    G_CALLBACK (on_RBSOUSTERRAIN_m_toggled),
                    NULL);
  g_signal_connect ((gpointer) RBSURFACE_m, "toggled",
                    G_CALLBACK (on_RBSURFACE_m_toggled),
                    NULL);
  g_signal_connect ((gpointer) RBAERIEN_m, "toggled",
                    G_CALLBACK (on_RBAERIEN_m_toggled),
                    NULL);
  g_signal_connect ((gpointer) Ajouter_PARKY, "clicked",
                    G_CALLBACK (on_Ajouter_PARKY_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher_fekher, "clicked",
                    G_CALLBACK (on_afficher_fekher_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_parking, "row_activated",
                    G_CALLBACK (on_treeview_parking_row_activated),
                    NULL);
  g_signal_connect ((gpointer) afficher_affect_agent, "clicked",
                    G_CALLBACK (on_afficher_affect_agent_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionParky, GestionParky, "GestionParky");
  GLADE_HOOKUP_OBJECT (GestionParky, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (GestionParky, ERECHERCHE, "ERECHERCHE");
  GLADE_HOOKUP_OBJECT (GestionParky, ENOM_m, "ENOM_m");
  GLADE_HOOKUP_OBJECT (GestionParky, ECAPACITE_m, "ECAPACITE_m");
  GLADE_HOOKUP_OBJECT (GestionParky, SBBLOC_m, "SBBLOC_m");
  GLADE_HOOKUP_OBJECT (GestionParky, SBJJ_m, "SBJJ_m");
  GLADE_HOOKUP_OBJECT (GestionParky, SBMM_m, "SBMM_m");
  GLADE_HOOKUP_OBJECT (GestionParky, SBYYYY_m, "SBYYYY_m");
  GLADE_HOOKUP_OBJECT (GestionParky, modifier_fekher, "modifier_fekher");
  GLADE_HOOKUP_OBJECT (GestionParky, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (GestionParky, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (GestionParky, image25, "image25");
  GLADE_HOOKUP_OBJECT (GestionParky, label57, "label57");
  GLADE_HOOKUP_OBJECT (GestionParky, supprimer_fekher, "supprimer_fekher");
  GLADE_HOOKUP_OBJECT (GestionParky, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (GestionParky, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (GestionParky, image16, "image16");
  GLADE_HOOKUP_OBJECT (GestionParky, label36, "label36");
  GLADE_HOOKUP_OBJECT (GestionParky, loop, "loop");
  GLADE_HOOKUP_OBJECT (GestionParky, image15, "image15");
  GLADE_HOOKUP_OBJECT (GestionParky, RBSOUSTERRAIN_m, "RBSOUSTERRAIN_m");
  GLADE_HOOKUP_OBJECT (GestionParky, RBSURFACE_m, "RBSURFACE_m");
  GLADE_HOOKUP_OBJECT (GestionParky, RBAERIEN_m, "RBAERIEN_m");
  GLADE_HOOKUP_OBJECT (GestionParky, CBREGION_m, "CBREGION_m");
  GLADE_HOOKUP_OBJECT (GestionParky, Ajouter_PARKY, "Ajouter_PARKY");
  GLADE_HOOKUP_OBJECT (GestionParky, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (GestionParky, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (GestionParky, image20, "image20");
  GLADE_HOOKUP_OBJECT (GestionParky, label41, "label41");
  GLADE_HOOKUP_OBJECT (GestionParky, label38, "label38");
  GLADE_HOOKUP_OBJECT (GestionParky, afficher_fekher, "afficher_fekher");
  GLADE_HOOKUP_OBJECT (GestionParky, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (GestionParky, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (GestionParky, image18, "image18");
  GLADE_HOOKUP_OBJECT (GestionParky, label39, "label39");
  GLADE_HOOKUP_OBJECT (GestionParky, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (GestionParky, treeview_parking, "treeview_parking");
  GLADE_HOOKUP_OBJECT (GestionParky, label42, "label42");
  GLADE_HOOKUP_OBJECT (GestionParky, label55, "label55");
  GLADE_HOOKUP_OBJECT (GestionParky, label54, "label54");
  GLADE_HOOKUP_OBJECT (GestionParky, label53, "label53");
  GLADE_HOOKUP_OBJECT (GestionParky, label52, "label52");
  GLADE_HOOKUP_OBJECT (GestionParky, label51, "label51");
  GLADE_HOOKUP_OBJECT (GestionParky, label56, "label56");
  GLADE_HOOKUP_OBJECT (GestionParky, image32, "image32");
  GLADE_HOOKUP_OBJECT (GestionParky, label43, "label43");
  GLADE_HOOKUP_OBJECT (GestionParky, afficher_affect_agent, "afficher_affect_agent");
  GLADE_HOOKUP_OBJECT (GestionParky, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (GestionParky, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (GestionParky, image33, "image33");
  GLADE_HOOKUP_OBJECT (GestionParky, label108, "label108");

  return GestionParky;
}

