/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_menu_Admin (void)
{
  GtkWidget *menu_Admin;
  GtkWidget *hbox1;
  GtkWidget *fixed7;
  GtkWidget *label105;
  GtkWidget *btnGestionAgent;
  GtkWidget *btnGestionCompte;
  GtkWidget *btnGestionService;
  GtkWidget *btnParking;
  GtkWidget *image52;

  menu_Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (menu_Admin), _("Menu"));
  gtk_window_set_position (GTK_WINDOW (menu_Admin), GTK_WIN_POS_CENTER_ON_PARENT);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (menu_Admin), hbox1);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_box_pack_start (GTK_BOX (hbox1), fixed7, TRUE, TRUE, 0);

  label105 = gtk_label_new (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"medium\">  Menu Administrateur  </span></u>"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed7), label105, 304, 24);
  gtk_widget_set_size_request (label105, 225, 32);
  gtk_label_set_use_markup (GTK_LABEL (label105), TRUE);

  btnGestionAgent = gtk_button_new_with_mnemonic (_("Gestion des Agents"));
  gtk_widget_show (btnGestionAgent);
  gtk_fixed_put (GTK_FIXED (fixed7), btnGestionAgent, 312, 80);
  gtk_widget_set_size_request (btnGestionAgent, 202, 37);

  btnGestionCompte = gtk_button_new_with_mnemonic (_("Gestion des Comptes"));
  gtk_widget_show (btnGestionCompte);
  gtk_fixed_put (GTK_FIXED (fixed7), btnGestionCompte, 312, 144);
  gtk_widget_set_size_request (btnGestionCompte, 202, 37);

  btnGestionService = gtk_button_new_with_mnemonic (_("Gestion des Services "));
  gtk_widget_show (btnGestionService);
  gtk_fixed_put (GTK_FIXED (fixed7), btnGestionService, 312, 280);
  gtk_widget_set_size_request (btnGestionService, 202, 37);

  btnParking = gtk_button_new_with_mnemonic (_("Gestion de Parking"));
  gtk_widget_show (btnParking);
  gtk_fixed_put (GTK_FIXED (fixed7), btnParking, 312, 208);
  gtk_widget_set_size_request (btnParking, 202, 37);

  image52 = create_pixmap (menu_Admin, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image52);
  gtk_fixed_put (GTK_FIXED (fixed7), image52, 40, 80);
  gtk_widget_set_size_request (image52, 240, 208);

  g_signal_connect ((gpointer) btnGestionAgent, "clicked",
                    G_CALLBACK (on_btnGestionAgent_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnGestionCompte, "clicked",
                    G_CALLBACK (on_btnGestionCompte_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnGestionService, "clicked",
                    G_CALLBACK (on_btnGestionService_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnParking, "clicked",
                    G_CALLBACK (on_btnParking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menu_Admin, menu_Admin, "menu_Admin");
  GLADE_HOOKUP_OBJECT (menu_Admin, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (menu_Admin, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (menu_Admin, label105, "label105");
  GLADE_HOOKUP_OBJECT (menu_Admin, btnGestionAgent, "btnGestionAgent");
  GLADE_HOOKUP_OBJECT (menu_Admin, btnGestionCompte, "btnGestionCompte");
  GLADE_HOOKUP_OBJECT (menu_Admin, btnGestionService, "btnGestionService");
  GLADE_HOOKUP_OBJECT (menu_Admin, btnParking, "btnParking");
  GLADE_HOOKUP_OBJECT (menu_Admin, image52, "image52");

  return menu_Admin;
}

GtkWidget*
create_Modification (void)
{
  GtkWidget *Modification;
  GtkWidget *fixed3;
  GtkObject *spinMinuteModRes_adj;
  GtkWidget *spinMinuteModRes;
  GtkObject *spinDureeModRes_adj;
  GtkWidget *spinDureeModRes;
  GtkObject *spinJourModRes_adj;
  GtkWidget *spinJourModRes;
  GtkObject *spinMoisModRes_adj;
  GtkWidget *spinMoisModRes;
  GtkObject *spinAnneeModRes_adj;
  GtkWidget *spinAnneeModRes;
  GtkObject *spinHeureModRes_adj;
  GtkWidget *spinHeureModRes;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *radioHeureModRes;
  GSList *radioHeureModRes_group = NULL;
  GtkWidget *radioJourModRes;
  GtkWidget *btnModifierRes;
  GtkWidget *alignment14;
  GtkWidget *hbox20;
  GtkWidget *image16;
  GtkWidget *label45;
  GtkWidget *labelErreurM;
  GtkWidget *btnAnnulerModRes;
  GtkWidget *alignment15;
  GtkWidget *hbox21;
  GtkWidget *image17;
  GtkWidget *label46;
  GtkWidget *image41;
  GtkWidget *label38;

  Modification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modification), _("Modification de la reservation"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Modification), fixed3);

  spinMinuteModRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinMinuteModRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinMinuteModRes_adj), 1, 0);
  gtk_widget_show (spinMinuteModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), spinMinuteModRes, 160, 200);
  gtk_widget_set_size_request (spinMinuteModRes, 192, 24);

  spinDureeModRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinDureeModRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinDureeModRes_adj), 1, 0);
  gtk_widget_show (spinDureeModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), spinDureeModRes, 112, 256);
  gtk_widget_set_size_request (spinDureeModRes, 96, 24);

  spinJourModRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinJourModRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinJourModRes_adj), 1, 0);
  gtk_widget_show (spinJourModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), spinJourModRes, 136, 72);
  gtk_widget_set_size_request (spinJourModRes, 60, 27);

  spinMoisModRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinMoisModRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinMoisModRes_adj), 1, 0);
  gtk_widget_show (spinMoisModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), spinMoisModRes, 208, 72);
  gtk_widget_set_size_request (spinMoisModRes, 60, 27);

  spinAnneeModRes_adj = gtk_adjustment_new (1, 0, 2090, 1, 10, 10);
  spinAnneeModRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinAnneeModRes_adj), 1, 0);
  gtk_widget_show (spinAnneeModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), spinAnneeModRes, 288, 72);
  gtk_widget_set_size_request (spinAnneeModRes, 60, 27);

  spinHeureModRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinHeureModRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinHeureModRes_adj), 1, 0);
  gtk_widget_show (spinHeureModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), spinHeureModRes, 152, 144);
  gtk_widget_set_size_request (spinHeureModRes, 200, 24);

  label40 = gtk_label_new (_("Date_Debut : "));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed3), label40, 40, 72);
  gtk_widget_set_size_request (label40, 96, 24);

  label41 = gtk_label_new (_("Heure_debut : "));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed3), label41, 40, 136);
  gtk_widget_set_size_request (label41, 104, 32);

  label42 = gtk_label_new (_("Minutes_debut : "));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed3), label42, 32, 184);
  gtk_widget_set_size_request (label42, 120, 40);

  label43 = gtk_label_new (_("Dur\303\251e : "));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed3), label43, 40, 256);
  gtk_widget_set_size_request (label43, 80, 24);

  radioHeureModRes = gtk_radio_button_new_with_mnemonic (NULL, _("Heures"));
  gtk_widget_show (radioHeureModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), radioHeureModRes, 216, 256);
  gtk_widget_set_size_request (radioHeureModRes, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioHeureModRes), radioHeureModRes_group);
  radioHeureModRes_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioHeureModRes));

  radioJourModRes = gtk_radio_button_new_with_mnemonic (NULL, _("Jours"));
  gtk_widget_show (radioJourModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), radioJourModRes, 312, 256);
  gtk_widget_set_size_request (radioJourModRes, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioJourModRes), radioHeureModRes_group);
  radioHeureModRes_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioJourModRes));

  btnModifierRes = gtk_button_new ();
  gtk_widget_show (btnModifierRes);
  gtk_fixed_put (GTK_FIXED (fixed3), btnModifierRes, 48, 344);
  gtk_widget_set_size_request (btnModifierRes, 104, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (btnModifierRes), alignment14);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox20);

  image16 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox20), image16, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox20), label45, FALSE, FALSE, 0);

  labelErreurM = gtk_label_new ("");
  gtk_widget_show (labelErreurM);
  gtk_fixed_put (GTK_FIXED (fixed3), labelErreurM, 88, 424);
  gtk_widget_set_size_request (labelErreurM, 272, 24);

  btnAnnulerModRes = gtk_button_new ();
  gtk_widget_show (btnAnnulerModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), btnAnnulerModRes, 272, 344);
  gtk_widget_set_size_request (btnAnnulerModRes, 96, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (btnAnnulerModRes), alignment15);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox21);

  image17 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox21), image17, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox21), label46, FALSE, FALSE, 0);

  image41 = create_pixmap (Modification, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image41);
  gtk_fixed_put (GTK_FIXED (fixed3), image41, 400, 72);
  gtk_widget_set_size_request (image41, 280, 208);

  label38 = gtk_label_new (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Modifier Reservation   </span></u>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed3), label38, 120, 8);
  gtk_widget_set_size_request (label38, 360, 48);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  g_signal_connect ((gpointer) radioHeureModRes, "toggled",
                    G_CALLBACK (on_radioHeureModRes_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioJourModRes, "toggled",
                    G_CALLBACK (on_radioJourModRes_toggled),
                    NULL);
  g_signal_connect ((gpointer) btnModifierRes, "clicked",
                    G_CALLBACK (on_btnModifierRes_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnAnnulerModRes, "clicked",
                    G_CALLBACK (on_btnAnnulerModRes_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modification, Modification, "Modification");
  GLADE_HOOKUP_OBJECT (Modification, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Modification, spinMinuteModRes, "spinMinuteModRes");
  GLADE_HOOKUP_OBJECT (Modification, spinDureeModRes, "spinDureeModRes");
  GLADE_HOOKUP_OBJECT (Modification, spinJourModRes, "spinJourModRes");
  GLADE_HOOKUP_OBJECT (Modification, spinMoisModRes, "spinMoisModRes");
  GLADE_HOOKUP_OBJECT (Modification, spinAnneeModRes, "spinAnneeModRes");
  GLADE_HOOKUP_OBJECT (Modification, spinHeureModRes, "spinHeureModRes");
  GLADE_HOOKUP_OBJECT (Modification, label40, "label40");
  GLADE_HOOKUP_OBJECT (Modification, label41, "label41");
  GLADE_HOOKUP_OBJECT (Modification, label42, "label42");
  GLADE_HOOKUP_OBJECT (Modification, label43, "label43");
  GLADE_HOOKUP_OBJECT (Modification, radioHeureModRes, "radioHeureModRes");
  GLADE_HOOKUP_OBJECT (Modification, radioJourModRes, "radioJourModRes");
  GLADE_HOOKUP_OBJECT (Modification, btnModifierRes, "btnModifierRes");
  GLADE_HOOKUP_OBJECT (Modification, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Modification, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Modification, image16, "image16");
  GLADE_HOOKUP_OBJECT (Modification, label45, "label45");
  GLADE_HOOKUP_OBJECT (Modification, labelErreurM, "labelErreurM");
  GLADE_HOOKUP_OBJECT (Modification, btnAnnulerModRes, "btnAnnulerModRes");
  GLADE_HOOKUP_OBJECT (Modification, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Modification, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (Modification, image17, "image17");
  GLADE_HOOKUP_OBJECT (Modification, label46, "label46");
  GLADE_HOOKUP_OBJECT (Modification, image41, "image41");
  GLADE_HOOKUP_OBJECT (Modification, label38, "label38");

  return Modification;
}

GtkWidget*
create_Menu_User (void)
{
  GtkWidget *Menu_User;
  GtkWidget *fixed4;
  GtkWidget *hbuttonbox7;
  GtkWidget *btnAfficherFactureM;
  GtkWidget *alignment38;
  GtkWidget *hbox44;
  GtkWidget *image40;
  GtkWidget *label94;
  GtkWidget *btnGestionAvis;
  GtkWidget *btnGestionReservation;
  GtkWidget *label44;
  GtkWidget *image15;

  Menu_User = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Menu_User), _("Menu Utilisateur"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Menu_User), fixed4);

  hbuttonbox7 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox7);
  gtk_fixed_put (GTK_FIXED (fixed4), hbuttonbox7, 216, 168);
  gtk_widget_set_size_request (hbuttonbox7, 170, 29);

  btnAfficherFactureM = gtk_button_new ();
  gtk_widget_show (btnAfficherFactureM);
  gtk_fixed_put (GTK_FIXED (fixed4), btnAfficherFactureM, 344, 288);
  gtk_widget_set_size_request (btnAfficherFactureM, 208, 29);

  alignment38 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment38);
  gtk_container_add (GTK_CONTAINER (btnAfficherFactureM), alignment38);

  hbox44 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox44);
  gtk_container_add (GTK_CONTAINER (alignment38), hbox44);

  image40 = gtk_image_new_from_stock ("gtk-print", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_box_pack_start (GTK_BOX (hbox44), image40, FALSE, FALSE, 0);

  label94 = gtk_label_new_with_mnemonic (_("Afficher Facture Mensuelle"));
  gtk_widget_show (label94);
  gtk_box_pack_start (GTK_BOX (hbox44), label94, FALSE, FALSE, 0);

  btnGestionAvis = gtk_button_new_with_mnemonic (_("Gestion des Avis et Reclamations"));
  gtk_widget_show (btnGestionAvis);
  gtk_fixed_put (GTK_FIXED (fixed4), btnGestionAvis, 336, 216);
  gtk_widget_set_size_request (btnGestionAvis, 240, 32);

  btnGestionReservation = gtk_button_new_with_mnemonic (_("Gestion Des Reservation"));
  gtk_widget_show (btnGestionReservation);
  gtk_fixed_put (GTK_FIXED (fixed4), btnGestionReservation, 360, 144);
  gtk_widget_set_size_request (btnGestionReservation, 176, 32);

  label44 = gtk_label_new (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"medium\">  Menu Utilisateur   </span></u>"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed4), label44, 344, 48);
  gtk_widget_set_size_request (label44, 208, 32);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  image15 = create_pixmap (Menu_User, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed4), image15, 0, 16);
  gtk_widget_set_size_request (image15, 368, 424);

  g_signal_connect ((gpointer) btnAfficherFactureM, "clicked",
                    G_CALLBACK (on_btnAfficherFactureM_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnGestionAvis, "clicked",
                    G_CALLBACK (on_btnGestionAvis_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnGestionReservation, "clicked",
                    G_CALLBACK (on_btnGestionReservation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Menu_User, Menu_User, "Menu_User");
  GLADE_HOOKUP_OBJECT (Menu_User, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Menu_User, hbuttonbox7, "hbuttonbox7");
  GLADE_HOOKUP_OBJECT (Menu_User, btnAfficherFactureM, "btnAfficherFactureM");
  GLADE_HOOKUP_OBJECT (Menu_User, alignment38, "alignment38");
  GLADE_HOOKUP_OBJECT (Menu_User, hbox44, "hbox44");
  GLADE_HOOKUP_OBJECT (Menu_User, image40, "image40");
  GLADE_HOOKUP_OBJECT (Menu_User, label94, "label94");
  GLADE_HOOKUP_OBJECT (Menu_User, btnGestionAvis, "btnGestionAvis");
  GLADE_HOOKUP_OBJECT (Menu_User, btnGestionReservation, "btnGestionReservation");
  GLADE_HOOKUP_OBJECT (Menu_User, label44, "label44");
  GLADE_HOOKUP_OBJECT (Menu_User, image15, "image15");

  return Menu_User;
}

GtkWidget*
create_Ajouter_Reservation (void)
{
  GtkWidget *Ajouter_Reservation;
  GtkWidget *_;
  GtkObject *spinJourRes_adj;
  GtkWidget *spinJourRes;
  GtkObject *spinMoisRes_adj;
  GtkWidget *spinMoisRes;
  GtkObject *spinAnneeRes_adj;
  GtkWidget *spinAnneeRes;
  GtkWidget *label61;
  GtkObject *spinHeureRes_adj;
  GtkWidget *spinHeureRes;
  GtkWidget *label62;
  GtkObject *spinMinuteRes_adj;
  GtkWidget *spinMinuteRes;
  GtkObject *spinDureeRes_adj;
  GtkWidget *spinDureeRes;
  GtkWidget *label63;
  GtkWidget *entryIdRes;
  GtkWidget *label85;
  GtkWidget *tvParkingA;
  GtkWidget *label59;
  GtkWidget *label86;
  GtkWidget *btnAnnulerAdd;
  GtkWidget *alignment25;
  GtkWidget *hbox31;
  GtkWidget *image27;
  GtkWidget *btnAnnuler;
  GtkWidget *label60;
  GtkWidget *labelErreur;
  GtkWidget *radioHeureRes;
  GSList *radioHeureRes_group = NULL;
  GtkWidget *radioJourRes;
  GtkWidget *btnAjouterRes;
  GtkWidget *alignment37;
  GtkWidget *hbox43;
  GtkWidget *image39;
  GtkWidget *label92;
  GtkWidget *comboRegion;
  GtkWidget *btnSearchPark;
  GtkWidget *alignment36;
  GtkWidget *hbox42;
  GtkWidget *image38;
  GtkWidget *label91;
  GtkWidget *image43;
  GtkWidget *label58;

  Ajouter_Reservation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter_Reservation), _("Nouvelle Reservation"));

  _ = gtk_fixed_new ();
  gtk_widget_show (_);
  gtk_container_add (GTK_CONTAINER (Ajouter_Reservation), _);

  spinJourRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinJourRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinJourRes_adj), 1, 0);
  gtk_widget_show (spinJourRes);
  gtk_fixed_put (GTK_FIXED (_), spinJourRes, 160, 128);
  gtk_widget_set_size_request (spinJourRes, 60, 27);

  spinMoisRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinMoisRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinMoisRes_adj), 1, 0);
  gtk_widget_show (spinMoisRes);
  gtk_fixed_put (GTK_FIXED (_), spinMoisRes, 232, 128);
  gtk_widget_set_size_request (spinMoisRes, 60, 27);

  spinAnneeRes_adj = gtk_adjustment_new (2024, 0, 2090, 1, 10, 10);
  spinAnneeRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinAnneeRes_adj), 0, 0);
  gtk_widget_show (spinAnneeRes);
  gtk_fixed_put (GTK_FIXED (_), spinAnneeRes, 312, 128);
  gtk_widget_set_size_request (spinAnneeRes, 60, 27);

  label61 = gtk_label_new (_("Heure_Debut : "));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (_), label61, 48, 208);
  gtk_widget_set_size_request (label61, 112, 24);

  spinHeureRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinHeureRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinHeureRes_adj), 1, 0);
  gtk_widget_show (spinHeureRes);
  gtk_fixed_put (GTK_FIXED (_), spinHeureRes, 168, 208);
  gtk_widget_set_size_request (spinHeureRes, 144, 24);

  label62 = gtk_label_new (_("Minute_Debut : "));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (_), label62, 56, 272);
  gtk_widget_set_size_request (label62, 112, 24);

  spinMinuteRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinMinuteRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinMinuteRes_adj), 1, 0);
  gtk_widget_show (spinMinuteRes);
  gtk_fixed_put (GTK_FIXED (_), spinMinuteRes, 176, 272);
  gtk_widget_set_size_request (spinMinuteRes, 152, 24);

  spinDureeRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinDureeRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinDureeRes_adj), 1, 0);
  gtk_widget_show (spinDureeRes);
  gtk_fixed_put (GTK_FIXED (_), spinDureeRes, 136, 344);
  gtk_widget_set_size_request (spinDureeRes, 144, 24);

  label63 = gtk_label_new (_("Duree : "));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (_), label63, 64, 352);
  gtk_widget_set_size_request (label63, 49, 17);

  entryIdRes = gtk_entry_new ();
  gtk_widget_show (entryIdRes);
  gtk_fixed_put (GTK_FIXED (_), entryIdRes, 200, 72);
  gtk_widget_set_size_request (entryIdRes, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIdRes), 8226);

  label85 = gtk_label_new (_("Region du Parking : "));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (_), label85, 56, 424);
  gtk_widget_set_size_request (label85, 144, 24);

  tvParkingA = gtk_tree_view_new ();
  gtk_widget_show (tvParkingA);
  gtk_fixed_put (GTK_FIXED (_), tvParkingA, 64, 528);
  gtk_widget_set_size_request (tvParkingA, 456, 136);

  label59 = gtk_label_new (_("ID de la Reservation : "));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (_), label59, 40, 72);
  gtk_widget_set_size_request (label59, 160, 24);

  label86 = gtk_label_new (_("Parking disponible"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (_), label86, 128, 488);
  gtk_widget_set_size_request (label86, 168, 24);

  btnAnnulerAdd = gtk_button_new ();
  gtk_widget_show (btnAnnulerAdd);
  gtk_fixed_put (GTK_FIXED (_), btnAnnulerAdd, 32, 680);
  gtk_widget_set_size_request (btnAnnulerAdd, 96, 29);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (btnAnnulerAdd), alignment25);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox31);

  image27 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox31), image27, FALSE, FALSE, 0);

  btnAnnuler = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (btnAnnuler);
  gtk_box_pack_start (GTK_BOX (hbox31), btnAnnuler, FALSE, FALSE, 0);

  label60 = gtk_label_new (_("Date_Debut : "));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (_), label60, 48, 136);
  gtk_widget_set_size_request (label60, 104, 24);

  labelErreur = gtk_label_new ("");
  gtk_widget_show (labelErreur);
  gtk_fixed_put (GTK_FIXED (_), labelErreur, 96, 712);
  gtk_widget_set_size_request (labelErreur, 320, 24);

  radioHeureRes = gtk_radio_button_new_with_mnemonic (NULL, _("Heure"));
  gtk_widget_show (radioHeureRes);
  gtk_fixed_put (GTK_FIXED (_), radioHeureRes, 288, 344);
  gtk_widget_set_size_request (radioHeureRes, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioHeureRes), radioHeureRes_group);
  radioHeureRes_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioHeureRes));

  radioJourRes = gtk_radio_button_new_with_mnemonic (NULL, _("Jour"));
  gtk_widget_show (radioJourRes);
  gtk_fixed_put (GTK_FIXED (_), radioJourRes, 360, 344);
  gtk_widget_set_size_request (radioJourRes, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioJourRes), radioHeureRes_group);
  radioHeureRes_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioJourRes));

  btnAjouterRes = gtk_button_new ();
  gtk_widget_show (btnAjouterRes);
  gtk_fixed_put (GTK_FIXED (_), btnAjouterRes, 368, 680);
  gtk_widget_set_size_request (btnAjouterRes, 96, 29);

  alignment37 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (btnAjouterRes), alignment37);

  hbox43 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox43);
  gtk_container_add (GTK_CONTAINER (alignment37), hbox43);

  image39 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_box_pack_start (GTK_BOX (hbox43), image39, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox43), label92, FALSE, FALSE, 0);

  comboRegion = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboRegion);
  gtk_fixed_put (GTK_FIXED (_), comboRegion, 208, 416);
  gtk_widget_set_size_request (comboRegion, 237, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Centre_ville_Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Sidi_Bousaid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("El_Manzeh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Lac1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Lac2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Carthage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Centre_ville_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Zone_Indus_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Centre_ville_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Azur_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Tunis_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Manar_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Tunisia_Mal"));

  btnSearchPark = gtk_button_new ();
  gtk_widget_show (btnSearchPark);
  gtk_fixed_put (GTK_FIXED (_), btnSearchPark, 456, 416);
  gtk_widget_set_size_request (btnSearchPark, 112, 32);

  alignment36 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment36);
  gtk_container_add (GTK_CONTAINER (btnSearchPark), alignment36);

  hbox42 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox42);
  gtk_container_add (GTK_CONTAINER (alignment36), hbox42);

  image38 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_box_pack_start (GTK_BOX (hbox42), image38, FALSE, FALSE, 0);

  label91 = gtk_label_new_with_mnemonic (_("Rechercher\n"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox42), label91, FALSE, FALSE, 0);

  image43 = create_pixmap (Ajouter_Reservation, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image43);
  gtk_fixed_put (GTK_FIXED (_), image43, 448, 112);
  gtk_widget_set_size_request (image43, 248, 208);

  label58 = gtk_label_new (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Ajouter une nouvelle Reservation    </span></u>"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (_), label58, 104, 16);
  gtk_widget_set_size_request (label58, 480, 32);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  g_signal_connect ((gpointer) tvParkingA, "row_activated",
                    G_CALLBACK (on_tvParkingA_row_activated),
                    NULL);
  g_signal_connect ((gpointer) btnAnnulerAdd, "clicked",
                    G_CALLBACK (on_btnAnnulerAdd_clicked),
                    NULL);
  g_signal_connect ((gpointer) radioHeureRes, "toggled",
                    G_CALLBACK (on_radioHeureRes_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioJourRes, "toggled",
                    G_CALLBACK (on_radioJourRes_toggled),
                    NULL);
  g_signal_connect ((gpointer) btnAjouterRes, "clicked",
                    G_CALLBACK (on_btnAjouterRes_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnSearchPark, "clicked",
                    G_CALLBACK (on_btnSearchPark_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_Reservation, Ajouter_Reservation, "Ajouter_Reservation");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, _, "_");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, spinJourRes, "spinJourRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, spinMoisRes, "spinMoisRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, spinAnneeRes, "spinAnneeRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label61, "label61");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, spinHeureRes, "spinHeureRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label62, "label62");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, spinMinuteRes, "spinMinuteRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, spinDureeRes, "spinDureeRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label63, "label63");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, entryIdRes, "entryIdRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label85, "label85");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, tvParkingA, "tvParkingA");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label59, "label59");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label86, "label86");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, btnAnnulerAdd, "btnAnnulerAdd");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, image27, "image27");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, btnAnnuler, "btnAnnuler");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label60, "label60");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, labelErreur, "labelErreur");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, radioHeureRes, "radioHeureRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, radioJourRes, "radioJourRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, btnAjouterRes, "btnAjouterRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, hbox43, "hbox43");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, image39, "image39");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label92, "label92");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, comboRegion, "comboRegion");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, btnSearchPark, "btnSearchPark");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, alignment36, "alignment36");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, hbox42, "hbox42");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, image38, "image38");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label91, "label91");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, image43, "image43");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label58, "label58");

  return Ajouter_Reservation;
}

GtkWidget*
create_Reservations_Listes (void)
{
  GtkWidget *Reservations_Listes;
  GtkWidget *fixed6;
  GtkWidget *label97;
  GtkWidget *label98;
  GtkObject *spinJourFl_adj;
  GtkWidget *spinJourFl;
  GtkObject *spinMoisFl_adj;
  GtkWidget *spinMoisFl;
  GtkObject *spinAnneeFl_adj;
  GtkWidget *spinAnneeFl;
  GtkWidget *tvReservation;
  GtkWidget *image50;
  GtkWidget *comboEtat;
  GtkWidget *checkStatus;
  GtkWidget *checkDateDebut;
  GtkWidget *label96;
  GtkWidget *btnFiltreRes;
  GtkWidget *alignment39;
  GtkWidget *hbox45;
  GtkWidget *image44;
  GtkWidget *label95;
  GtkWidget *btnTriRes;
  GtkWidget *alignment40;
  GtkWidget *hbox46;
  GtkWidget *image45;
  GtkWidget *label99;
  GtkWidget *btnAjouterFl;
  GtkWidget *alignment41;
  GtkWidget *hbox47;
  GtkWidget *image46;
  GtkWidget *label100;
  GtkWidget *btnModifierFl;
  GtkWidget *alignment45;
  GtkWidget *hbox51;
  GtkWidget *image51;
  GtkWidget *label104;
  GtkWidget *btnAnnulerRes;
  GtkWidget *alignment43;
  GtkWidget *hbox49;
  GtkWidget *image48;
  GtkWidget *label102;
  GtkWidget *btnSupprimerFl;
  GtkWidget *alignment44;
  GtkWidget *hbox50;
  GtkWidget *image49;
  GtkWidget *label103;
  GtkWidget *btnAcceuilFl;
  GtkWidget *alignment46;
  GtkWidget *hbox52;
  GtkWidget *image53;
  GtkWidget *label106;

  Reservations_Listes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Reservations_Listes), _("Reservations Listes"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Reservations_Listes), fixed6);

  label97 = gtk_label_new (_("Status : "));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed6), label97, 456, 96);
  gtk_widget_set_size_request (label97, 72, 25);

  label98 = gtk_label_new (_("Date Debut : "));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed6), label98, 448, 136);
  gtk_widget_set_size_request (label98, 120, 25);

  spinJourFl_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spinJourFl = gtk_spin_button_new (GTK_ADJUSTMENT (spinJourFl_adj), 1, 0);
  gtk_widget_show (spinJourFl);
  gtk_fixed_put (GTK_FIXED (fixed6), spinJourFl, 592, 136);
  gtk_widget_set_size_request (spinJourFl, 60, 27);

  spinMoisFl_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinMoisFl = gtk_spin_button_new (GTK_ADJUSTMENT (spinMoisFl_adj), 1, 0);
  gtk_widget_show (spinMoisFl);
  gtk_fixed_put (GTK_FIXED (fixed6), spinMoisFl, 672, 136);
  gtk_widget_set_size_request (spinMoisFl, 60, 27);

  spinAnneeFl_adj = gtk_adjustment_new (2024, 2024, 2090, 1, 10, 10);
  spinAnneeFl = gtk_spin_button_new (GTK_ADJUSTMENT (spinAnneeFl_adj), 1, 0);
  gtk_widget_show (spinAnneeFl);
  gtk_fixed_put (GTK_FIXED (fixed6), spinAnneeFl, 760, 136);
  gtk_widget_set_size_request (spinAnneeFl, 60, 27);

  tvReservation = gtk_tree_view_new ();
  gtk_widget_show (tvReservation);
  gtk_fixed_put (GTK_FIXED (fixed6), tvReservation, 144, 224);
  gtk_widget_set_size_request (tvReservation, 640, 320);

  image50 = create_pixmap (Reservations_Listes, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image50);
  gtk_fixed_put (GTK_FIXED (fixed6), image50, 840, 224);
  gtk_widget_set_size_request (image50, 352, 288);

  comboEtat = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboEtat);
  gtk_fixed_put (GTK_FIXED (fixed6), comboEtat, 616, 96);
  gtk_widget_set_size_request (comboEtat, 205, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboEtat), _("Annulee"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboEtat), _("Validee"));

  checkStatus = gtk_check_button_new_with_mnemonic (_("Status"));
  gtk_widget_show (checkStatus);
  gtk_fixed_put (GTK_FIXED (fixed6), checkStatus, 304, 96);
  gtk_widget_set_size_request (checkStatus, 118, 24);

  checkDateDebut = gtk_check_button_new_with_mnemonic (_("Date Debut"));
  gtk_widget_show (checkDateDebut);
  gtk_fixed_put (GTK_FIXED (fixed6), checkDateDebut, 304, 136);
  gtk_widget_set_size_request (checkDateDebut, 118, 24);

  label96 = gtk_label_new (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Listes de mes Reservations   </span></u>"));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed6), label96, 408, 16);
  gtk_widget_set_size_request (label96, 392, 56);
  gtk_label_set_use_markup (GTK_LABEL (label96), TRUE);

  btnFiltreRes = gtk_button_new ();
  gtk_widget_show (btnFiltreRes);
  gtk_fixed_put (GTK_FIXED (fixed6), btnFiltreRes, 72, 88);
  gtk_widget_set_size_request (btnFiltreRes, 120, 48);

  alignment39 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment39);
  gtk_container_add (GTK_CONTAINER (btnFiltreRes), alignment39);

  hbox45 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox45);
  gtk_container_add (GTK_CONTAINER (alignment39), hbox45);

  image44 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image44);
  gtk_box_pack_start (GTK_BOX (hbox45), image44, FALSE, FALSE, 0);

  label95 = gtk_label_new_with_mnemonic (_("Filtrer"));
  gtk_widget_show (label95);
  gtk_box_pack_start (GTK_BOX (hbox45), label95, FALSE, FALSE, 0);

  btnTriRes = gtk_button_new ();
  gtk_widget_show (btnTriRes);
  gtk_fixed_put (GTK_FIXED (fixed6), btnTriRes, 56, 600);
  gtk_widget_set_size_request (btnTriRes, 104, 37);

  alignment40 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment40);
  gtk_container_add (GTK_CONTAINER (btnTriRes), alignment40);

  hbox46 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox46);
  gtk_container_add (GTK_CONTAINER (alignment40), hbox46);

  image45 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image45);
  gtk_box_pack_start (GTK_BOX (hbox46), image45, FALSE, FALSE, 0);

  label99 = gtk_label_new_with_mnemonic (_("Trier"));
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (hbox46), label99, FALSE, FALSE, 0);

  btnAjouterFl = gtk_button_new ();
  gtk_widget_show (btnAjouterFl);
  gtk_fixed_put (GTK_FIXED (fixed6), btnAjouterFl, 56, 696);
  gtk_widget_set_size_request (btnAjouterFl, 112, 40);

  alignment41 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment41);
  gtk_container_add (GTK_CONTAINER (btnAjouterFl), alignment41);

  hbox47 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox47);
  gtk_container_add (GTK_CONTAINER (alignment41), hbox47);

  image46 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image46);
  gtk_box_pack_start (GTK_BOX (hbox47), image46, FALSE, FALSE, 0);

  label100 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox47), label100, FALSE, FALSE, 0);

  btnModifierFl = gtk_button_new ();
  gtk_widget_show (btnModifierFl);
  gtk_fixed_put (GTK_FIXED (fixed6), btnModifierFl, 368, 632);
  gtk_widget_set_size_request (btnModifierFl, 120, 40);

  alignment45 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment45);
  gtk_container_add (GTK_CONTAINER (btnModifierFl), alignment45);

  hbox51 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox51);
  gtk_container_add (GTK_CONTAINER (alignment45), hbox51);

  image51 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image51);
  gtk_box_pack_start (GTK_BOX (hbox51), image51, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox51), label104, FALSE, FALSE, 0);

  btnAnnulerRes = gtk_button_new ();
  gtk_widget_show (btnAnnulerRes);
  gtk_fixed_put (GTK_FIXED (fixed6), btnAnnulerRes, 664, 592);
  gtk_widget_set_size_request (btnAnnulerRes, 184, 40);

  alignment43 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment43);
  gtk_container_add (GTK_CONTAINER (btnAnnulerRes), alignment43);

  hbox49 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox49);
  gtk_container_add (GTK_CONTAINER (alignment43), hbox49);

  image48 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image48);
  gtk_box_pack_start (GTK_BOX (hbox49), image48, FALSE, FALSE, 0);

  label102 = gtk_label_new_with_mnemonic (_("Annuler Reservation"));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (hbox49), label102, FALSE, FALSE, 0);

  btnSupprimerFl = gtk_button_new ();
  gtk_widget_show (btnSupprimerFl);
  gtk_fixed_put (GTK_FIXED (fixed6), btnSupprimerFl, 728, 688);
  gtk_widget_set_size_request (btnSupprimerFl, 120, 40);

  alignment44 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment44);
  gtk_container_add (GTK_CONTAINER (btnSupprimerFl), alignment44);

  hbox50 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox50);
  gtk_container_add (GTK_CONTAINER (alignment44), hbox50);

  image49 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image49);
  gtk_box_pack_start (GTK_BOX (hbox50), image49, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox50), label103, FALSE, FALSE, 0);

  btnAcceuilFl = gtk_button_new ();
  gtk_widget_show (btnAcceuilFl);
  gtk_fixed_put (GTK_FIXED (fixed6), btnAcceuilFl, 1024, 88);
  gtk_widget_set_size_request (btnAcceuilFl, 114, 45);

  alignment46 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment46);
  gtk_container_add (GTK_CONTAINER (btnAcceuilFl), alignment46);

  hbox52 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox52);
  gtk_container_add (GTK_CONTAINER (alignment46), hbox52);

  image53 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_box_pack_start (GTK_BOX (hbox52), image53, FALSE, FALSE, 0);

  label106 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (hbox52), label106, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) tvReservation, "row_activated",
                    G_CALLBACK (on_tvReservation_row_activated),
                    NULL);
  g_signal_connect ((gpointer) checkStatus, "toggled",
                    G_CALLBACK (on_checkStatus_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkDateDebut, "toggled",
                    G_CALLBACK (on_checkDateDebut_toggled),
                    NULL);
  g_signal_connect ((gpointer) btnFiltreRes, "clicked",
                    G_CALLBACK (on_btnFiltreRes_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnTriRes, "clicked",
                    G_CALLBACK (on_btnTriRes_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnAjouterFl, "clicked",
                    G_CALLBACK (on_btnAjouterFl_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnModifierFl, "clicked",
                    G_CALLBACK (on_btnModifierFl_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnAnnulerRes, "clicked",
                    G_CALLBACK (on_btnAnnulerRes_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnSupprimerFl, "clicked",
                    G_CALLBACK (on_btnSupprimerFl_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnAcceuilFl, "clicked",
                    G_CALLBACK (on_btnAcceuilFl_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Reservations_Listes, Reservations_Listes, "Reservations_Listes");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label97, "label97");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label98, "label98");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, spinJourFl, "spinJourFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, spinMoisFl, "spinMoisFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, spinAnneeFl, "spinAnneeFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, tvReservation, "tvReservation");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image50, "image50");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, comboEtat, "comboEtat");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, checkStatus, "checkStatus");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, checkDateDebut, "checkDateDebut");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label96, "label96");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnFiltreRes, "btnFiltreRes");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment39, "alignment39");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox45, "hbox45");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image44, "image44");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label95, "label95");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnTriRes, "btnTriRes");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment40, "alignment40");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox46, "hbox46");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image45, "image45");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label99, "label99");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnAjouterFl, "btnAjouterFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment41, "alignment41");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox47, "hbox47");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image46, "image46");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label100, "label100");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnModifierFl, "btnModifierFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment45, "alignment45");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox51, "hbox51");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image51, "image51");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label104, "label104");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnAnnulerRes, "btnAnnulerRes");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment43, "alignment43");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox49, "hbox49");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image48, "image48");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label102, "label102");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnSupprimerFl, "btnSupprimerFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment44, "alignment44");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox50, "hbox50");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image49, "image49");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label103, "label103");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnAcceuilFl, "btnAcceuilFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment46, "alignment46");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox52, "hbox52");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image53, "image53");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label106, "label106");

  return Reservations_Listes;
}

GtkWidget*
create_Ajout (void)
{
  GtkWidget *Ajout;
  GtkWidget *fixed1;
  GtkWidget *EID;
  GtkWidget *ENOM;
  GtkObject *SBJJ_ajout_adj;
  GtkWidget *SBJJ_ajout;
  GtkObject *SBMM_ajout_adj;
  GtkWidget *SBMM_ajout;
  GtkObject *SBBLOC_ajout_adj;
  GtkWidget *SBBLOC_ajout;
  GtkWidget *ECAPACITE;
  GtkObject *SBYYYY_ajout_adj;
  GtkWidget *SBYYYY_ajout;
  GtkWidget *annuler;
  GtkWidget *image2;
  GtkWidget *ajouter_parking;
  GtkWidget *image1;
  GtkWidget *label99;
  GtkWidget *image30;
  GtkWidget *CBREGION_ajout;
  GtkWidget *label3;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label23;
  GtkWidget *label25;
  GtkWidget *RBSURFACE;
  GSList *RBSURFACE_group = NULL;
  GtkWidget *RBSOUSTERRAIN;
  GtkWidget *label49;
  GtkWidget *label4;
  GtkWidget *confirmation_fekher;
  GtkWidget *alignment20;
  GtkWidget *hbox19;
  GtkWidget *image34;
  GtkWidget *label109;
  GtkWidget *RBAERIEN;

  Ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajout), _("ajout"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Ajout), fixed1);

  EID = gtk_entry_new ();
  gtk_widget_show (EID);
  gtk_fixed_put (GTK_FIXED (fixed1), EID, 176, 104);
  gtk_widget_set_size_request (EID, 172, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (EID), 8226);

  ENOM = gtk_entry_new ();
  gtk_widget_show (ENOM);
  gtk_fixed_put (GTK_FIXED (fixed1), ENOM, 176, 152);
  gtk_widget_set_size_request (ENOM, 172, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (ENOM), 8226);

  SBJJ_ajout_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  SBJJ_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (SBJJ_ajout_adj), 1, 0);
  gtk_widget_show (SBJJ_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), SBJJ_ajout, 136, 464);
  gtk_widget_set_size_request (SBJJ_ajout, 50, 28);

  SBMM_ajout_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  SBMM_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (SBMM_ajout_adj), 1, 0);
  gtk_widget_show (SBMM_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), SBMM_ajout, 216, 464);
  gtk_widget_set_size_request (SBMM_ajout, 50, 28);

  SBBLOC_ajout_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  SBBLOC_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (SBBLOC_ajout_adj), 1, 0);
  gtk_widget_show (SBBLOC_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), SBBLOC_ajout, 176, 304);
  gtk_widget_set_size_request (SBBLOC_ajout, 50, 28);

  ECAPACITE = gtk_entry_new ();
  gtk_widget_show (ECAPACITE);
  gtk_fixed_put (GTK_FIXED (fixed1), ECAPACITE, 176, 256);
  gtk_widget_set_size_request (ECAPACITE, 172, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (ECAPACITE), 8226);

  SBYYYY_ajout_adj = gtk_adjustment_new (2024, 2024, 2060, 1, 10, 10);
  SBYYYY_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (SBYYYY_ajout_adj), 1, 0);
  gtk_widget_show (SBYYYY_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), SBYYYY_ajout, 288, 464);
  gtk_widget_set_size_request (SBYYYY_ajout, 70, 29);

  annuler = gtk_button_new ();
  gtk_widget_show (annuler);
  gtk_fixed_put (GTK_FIXED (fixed1), annuler, 288, 560);
  gtk_widget_set_size_request (annuler, 90, 50);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (annuler), image2);

  ajouter_parking = gtk_button_new ();
  gtk_widget_show (ajouter_parking);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter_parking, 104, 560);
  gtk_widget_set_size_request (ajouter_parking, 88, 50);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (ajouter_parking), image1);

  label99 = gtk_label_new_with_mnemonic (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Ajouter un parking  </span></u>"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed1), label99, 264, 16);
  gtk_widget_set_size_request (label99, 272, 56);
  gtk_label_set_use_markup (GTK_LABEL (label99), TRUE);

  image30 = create_pixmap (Ajout, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed1), image30, 408, 128);
  gtk_widget_set_size_request (image30, 352, 272);

  CBREGION_ajout = gtk_combo_box_new_text ();
  gtk_widget_show (CBREGION_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), CBREGION_ajout, 176, 200);
  gtk_widget_set_size_request (CBREGION_ajout, 240, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Centre_ville_Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Sidi_Bousaid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("El_Manzeh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Lac1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Lac2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Carthage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Centre_ville_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Zone_Indus_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Centre_Ville_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Zone_Indus_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Azur_City  "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Tunis_City "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Manar_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_ajout), _("Tunisia_Mall "));

  label3 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Region de parking</span>"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 0, 200);
  gtk_widget_set_size_request (label3, 168, 32);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  label1 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Nom de parking</span>"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 24, 152);
  gtk_widget_set_size_request (label1, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  label2 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Id parking</span>"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 64, 104);
  gtk_widget_set_size_request (label2, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  label23 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Capacit\303\251</span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed1), label23, 56, 256);
  gtk_widget_set_size_request (label23, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label25 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Nombre de blocs</span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed1), label25, 8, 304);
  gtk_widget_set_size_request (label25, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  RBSURFACE = gtk_radio_button_new_with_mnemonic (NULL, _("sur surface"));
  gtk_widget_show (RBSURFACE);
  gtk_fixed_put (GTK_FIXED (fixed1), RBSURFACE, 176, 384);
  gtk_widget_set_size_request (RBSURFACE, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RBSURFACE), RBSURFACE_group);
  RBSURFACE_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RBSURFACE));

  RBSOUSTERRAIN = gtk_radio_button_new_with_mnemonic (NULL, _("sous-terrain"));
  gtk_widget_show (RBSOUSTERRAIN);
  gtk_fixed_put (GTK_FIXED (fixed1), RBSOUSTERRAIN, 176, 416);
  gtk_widget_set_size_request (RBSOUSTERRAIN, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RBSOUSTERRAIN), RBSURFACE_group);
  RBSURFACE_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RBSOUSTERRAIN));

  label49 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Type de parking</span>"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed1), label49, 8, 384);
  gtk_widget_set_size_request (label49, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  label4 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Date d'ajout</span>"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 0, 464);
  gtk_widget_set_size_request (label4, 128, 24);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  confirmation_fekher = gtk_check_button_new ();
  gtk_widget_show (confirmation_fekher);
  gtk_fixed_put (GTK_FIXED (fixed1), confirmation_fekher, 168, 504);
  gtk_widget_set_size_request (confirmation_fekher, 136, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (confirmation_fekher), alignment20);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox19);

  image34 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox19), image34, FALSE, FALSE, 0);

  label109 = gtk_label_new_with_mnemonic (_("Confirmation"));
  gtk_widget_show (label109);
  gtk_box_pack_start (GTK_BOX (hbox19), label109, FALSE, FALSE, 0);

  RBAERIEN = gtk_radio_button_new_with_mnemonic (NULL, _("a\303\251rien"));
  gtk_widget_show (RBAERIEN);
  gtk_fixed_put (GTK_FIXED (fixed1), RBAERIEN, 176, 352);
  gtk_widget_set_size_request (RBAERIEN, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RBAERIEN), RBSURFACE_group);
  RBSURFACE_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RBAERIEN));

  g_signal_connect ((gpointer) annuler, "clicked",
                    G_CALLBACK (on_annuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_parking, "clicked",
                    G_CALLBACK (on_ajouter_parking_clicked),
                    NULL);
  g_signal_connect ((gpointer) RBSURFACE, "toggled",
                    G_CALLBACK (on_RBSURFACE_toggled),
                    NULL);
  g_signal_connect ((gpointer) RBSOUSTERRAIN, "toggled",
                    G_CALLBACK (on_RBSOUSTERRAIN_toggled),
                    NULL);
  g_signal_connect ((gpointer) confirmation_fekher, "toggled",
                    G_CALLBACK (on_confirmation_fekher_toggled),
                    NULL);
  g_signal_connect ((gpointer) RBAERIEN, "toggled",
                    G_CALLBACK (on_RBAERIEN_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout, Ajout, "Ajout");
  GLADE_HOOKUP_OBJECT (Ajout, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Ajout, EID, "EID");
  GLADE_HOOKUP_OBJECT (Ajout, ENOM, "ENOM");
  GLADE_HOOKUP_OBJECT (Ajout, SBJJ_ajout, "SBJJ_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, SBMM_ajout, "SBMM_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, SBBLOC_ajout, "SBBLOC_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, ECAPACITE, "ECAPACITE");
  GLADE_HOOKUP_OBJECT (Ajout, SBYYYY_ajout, "SBYYYY_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, annuler, "annuler");
  GLADE_HOOKUP_OBJECT (Ajout, image2, "image2");
  GLADE_HOOKUP_OBJECT (Ajout, ajouter_parking, "ajouter_parking");
  GLADE_HOOKUP_OBJECT (Ajout, image1, "image1");
  GLADE_HOOKUP_OBJECT (Ajout, label99, "label99");
  GLADE_HOOKUP_OBJECT (Ajout, image30, "image30");
  GLADE_HOOKUP_OBJECT (Ajout, CBREGION_ajout, "CBREGION_ajout");
  GLADE_HOOKUP_OBJECT (Ajout, label3, "label3");
  GLADE_HOOKUP_OBJECT (Ajout, label1, "label1");
  GLADE_HOOKUP_OBJECT (Ajout, label2, "label2");
  GLADE_HOOKUP_OBJECT (Ajout, label23, "label23");
  GLADE_HOOKUP_OBJECT (Ajout, label25, "label25");
  GLADE_HOOKUP_OBJECT (Ajout, RBSURFACE, "RBSURFACE");
  GLADE_HOOKUP_OBJECT (Ajout, RBSOUSTERRAIN, "RBSOUSTERRAIN");
  GLADE_HOOKUP_OBJECT (Ajout, label49, "label49");
  GLADE_HOOKUP_OBJECT (Ajout, label4, "label4");
  GLADE_HOOKUP_OBJECT (Ajout, confirmation_fekher, "confirmation_fekher");
  GLADE_HOOKUP_OBJECT (Ajout, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Ajout, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Ajout, image34, "image34");
  GLADE_HOOKUP_OBJECT (Ajout, label109, "label109");
  GLADE_HOOKUP_OBJECT (Ajout, RBAERIEN, "RBAERIEN");

  return Ajout;
}

GtkWidget*
create_affectation (void)
{
  GtkWidget *affectation;
  GtkWidget *fixed4;
  GtkWidget *label107;
  GtkWidget *return_affect;
  GtkWidget *alignment17;
  GtkWidget *hbox16;
  GtkWidget *image26;
  GtkWidget *label103;
  GtkWidget *treeview1;
  GtkWidget *image31;
  GtkWidget *label101;
  GtkWidget *entry_agent_affect;
  GtkWidget *annuler_affectation;
  GtkWidget *alignment18;
  GtkWidget *hbox17;
  GtkWidget *image27;
  GtkWidget *label104;
  GtkWidget *affectation_agent;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image10;
  GtkWidget *label12;

  affectation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affectation), _("affectation"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (affectation), fixed4);

  label107 = gtk_label_new_with_mnemonic (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Affectation d'un agent   </span></u>"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed4), label107, 176, 16);
  gtk_widget_set_size_request (label107, 328, 40);
  gtk_label_set_use_markup (GTK_LABEL (label107), TRUE);

  return_affect = gtk_button_new ();
  gtk_widget_show (return_affect);
  gtk_fixed_put (GTK_FIXED (fixed4), return_affect, 24, 16);
  gtk_widget_set_size_request (return_affect, 74, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (return_affect), alignment17);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox16);

  image26 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox16), image26, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("return"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox16), label103, FALSE, FALSE, 0);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview1, 80, 248);
  gtk_widget_set_size_request (treeview1, 616, 208);

  image31 = create_pixmap (affectation, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed4), image31, 528, 24);
  gtk_widget_set_size_request (image31, 256, 208);

  label101 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Selectionner un agent :</span>"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed4), label101, 32, 112);
  gtk_widget_set_size_request (label101, 200, 48);
  gtk_label_set_use_markup (GTK_LABEL (label101), TRUE);

  entry_agent_affect = gtk_entry_new ();
  gtk_widget_show (entry_agent_affect);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_agent_affect, 272, 120);
  gtk_widget_set_size_request (entry_agent_affect, 208, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_agent_affect), 8226);

  annuler_affectation = gtk_button_new ();
  gtk_widget_show (annuler_affectation);
  gtk_fixed_put (GTK_FIXED (fixed4), annuler_affectation, 512, 496);
  gtk_widget_set_size_request (annuler_affectation, 142, 41);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (annuler_affectation), alignment18);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox17);

  image27 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox17), image27, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox17), label104, FALSE, FALSE, 0);

  affectation_agent = gtk_button_new ();
  gtk_widget_show (affectation_agent);
  gtk_fixed_put (GTK_FIXED (fixed4), affectation_agent, 96, 496);
  gtk_widget_set_size_request (affectation_agent, 150, 41);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (affectation_agent), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox2), image10, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Affecter"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox2), label12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) return_affect, "clicked",
                    G_CALLBACK (on_return_affect_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) annuler_affectation, "clicked",
                    G_CALLBACK (on_annuler_affectation_clicked),
                    NULL);
  g_signal_connect ((gpointer) affectation_agent, "clicked",
                    G_CALLBACK (on_affectation_agent_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affectation, affectation, "affectation");
  GLADE_HOOKUP_OBJECT (affectation, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (affectation, label107, "label107");
  GLADE_HOOKUP_OBJECT (affectation, return_affect, "return_affect");
  GLADE_HOOKUP_OBJECT (affectation, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (affectation, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (affectation, image26, "image26");
  GLADE_HOOKUP_OBJECT (affectation, label103, "label103");
  GLADE_HOOKUP_OBJECT (affectation, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (affectation, image31, "image31");
  GLADE_HOOKUP_OBJECT (affectation, label101, "label101");
  GLADE_HOOKUP_OBJECT (affectation, entry_agent_affect, "entry_agent_affect");
  GLADE_HOOKUP_OBJECT (affectation, annuler_affectation, "annuler_affectation");
  GLADE_HOOKUP_OBJECT (affectation, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (affectation, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (affectation, image27, "image27");
  GLADE_HOOKUP_OBJECT (affectation, label104, "label104");
  GLADE_HOOKUP_OBJECT (affectation, affectation_agent, "affectation_agent");
  GLADE_HOOKUP_OBJECT (affectation, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (affectation, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (affectation, image10, "image10");
  GLADE_HOOKUP_OBJECT (affectation, label12, "label12");

  return affectation;
}

GtkWidget*
create_GestionParky (void)
{
  GtkWidget *GestionParky;
  GtkWidget *fixed5;
  GtkWidget *ERECHERCHE;
  GtkWidget *ENOM_m;
  GtkWidget *ECAPACITE_m;
  GtkObject *SBBLOC_m_adj;
  GtkWidget *SBBLOC_m;
  GtkObject *SBJJ_m_adj;
  GtkWidget *SBJJ_m;
  GtkObject *SBMM_m_adj;
  GtkWidget *SBMM_m;
  GtkObject *SBYYYY_m_adj;
  GtkWidget *SBYYYY_m;
  GtkWidget *modifier_fekher;
  GtkWidget *alignment16;
  GtkWidget *hbox15;
  GtkWidget *image25;
  GtkWidget *label57;
  GtkWidget *supprimer_fekher;
  GtkWidget *alignment8;
  GtkWidget *hbox7;
  GtkWidget *image16;
  GtkWidget *label36;
  GtkWidget *loop;
  GtkWidget *image15;
  GtkWidget *RBSOUSTERRAIN_m;
  GSList *RBSOUSTERRAIN_m_group = NULL;
  GtkWidget *RBSURFACE_m;
  GtkWidget *RBAERIEN_m;
  GtkWidget *CBREGION_m;
  GtkWidget *Ajouter_PARKY;
  GtkWidget *alignment12;
  GtkWidget *hbox11;
  GtkWidget *image20;
  GtkWidget *label41;
  GtkWidget *label38;
  GtkWidget *afficher_fekher;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image18;
  GtkWidget *label39;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_parking;
  GtkWidget *label42;
  GtkWidget *label55;
  GtkWidget *label54;
  GtkWidget *label53;
  GtkWidget *label52;
  GtkWidget *label51;
  GtkWidget *label56;
  GtkWidget *image32;
  GtkWidget *label43;
  GtkWidget *afficher_affect_agent;
  GtkWidget *alignment19;
  GtkWidget *hbox18;
  GtkWidget *image33;
  GtkWidget *label108;

  GestionParky = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GestionParky), _("gestions des Parking"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (GestionParky), fixed5);

  ERECHERCHE = gtk_entry_new ();
  gtk_widget_show (ERECHERCHE);
  gtk_fixed_put (GTK_FIXED (fixed5), ERECHERCHE, 832, 56);
  gtk_widget_set_size_request (ERECHERCHE, 208, 35);
  gtk_entry_set_text (GTK_ENTRY (ERECHERCHE), "Id ...");
  gtk_entry_set_invisible_char (GTK_ENTRY (ERECHERCHE), 46);

  ENOM_m = gtk_entry_new ();
  gtk_widget_show (ENOM_m);
  gtk_fixed_put (GTK_FIXED (fixed5), ENOM_m, 904, 224);
  gtk_widget_set_size_request (ENOM_m, 224, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (ENOM_m), 8226);

  ECAPACITE_m = gtk_entry_new ();
  gtk_widget_show (ECAPACITE_m);
  gtk_fixed_put (GTK_FIXED (fixed5), ECAPACITE_m, 904, 320);
  gtk_widget_set_size_request (ECAPACITE_m, 224, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (ECAPACITE_m), 8226);

  SBBLOC_m_adj = gtk_adjustment_new (1, 1, 10, 1, 10, 10);
  SBBLOC_m = gtk_spin_button_new (GTK_ADJUSTMENT (SBBLOC_m_adj), 1, 0);
  gtk_widget_show (SBBLOC_m);
  gtk_fixed_put (GTK_FIXED (fixed5), SBBLOC_m, 904, 368);
  gtk_widget_set_size_request (SBBLOC_m, 50, 28);

  SBJJ_m_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  SBJJ_m = gtk_spin_button_new (GTK_ADJUSTMENT (SBJJ_m_adj), 1, 0);
  gtk_widget_show (SBJJ_m);
  gtk_fixed_put (GTK_FIXED (fixed5), SBJJ_m, 888, 520);
  gtk_widget_set_size_request (SBJJ_m, 50, 28);

  SBMM_m_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  SBMM_m = gtk_spin_button_new (GTK_ADJUSTMENT (SBMM_m_adj), 1, 0);
  gtk_widget_show (SBMM_m);
  gtk_fixed_put (GTK_FIXED (fixed5), SBMM_m, 952, 520);
  gtk_widget_set_size_request (SBMM_m, 50, 28);

  SBYYYY_m_adj = gtk_adjustment_new (2024, 2024, 2060, 1, 10, 10);
  SBYYYY_m = gtk_spin_button_new (GTK_ADJUSTMENT (SBYYYY_m_adj), 1, 0);
  gtk_widget_show (SBYYYY_m);
  gtk_fixed_put (GTK_FIXED (fixed5), SBYYYY_m, 1016, 520);
  gtk_widget_set_size_request (SBYYYY_m, 70, 29);

  modifier_fekher = gtk_button_new ();
  gtk_widget_show (modifier_fekher);
  gtk_fixed_put (GTK_FIXED (fixed5), modifier_fekher, 888, 584);
  gtk_widget_set_size_request (modifier_fekher, 150, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (modifier_fekher), alignment16);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox15);

  image25 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox15), image25, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox15), label57, FALSE, FALSE, 0);

  supprimer_fekher = gtk_button_new ();
  gtk_widget_show (supprimer_fekher);
  gtk_fixed_put (GTK_FIXED (fixed5), supprimer_fekher, 240, 584);
  gtk_widget_set_size_request (supprimer_fekher, 150, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (supprimer_fekher), alignment8);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox7);

  image16 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox7), image16, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox7), label36, FALSE, FALSE, 0);

  loop = gtk_button_new ();
  gtk_widget_show (loop);
  gtk_fixed_put (GTK_FIXED (fixed5), loop, 1048, 56);
  gtk_widget_set_size_request (loop, 64, 37);

  image15 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_container_add (GTK_CONTAINER (loop), image15);

  RBSOUSTERRAIN_m = gtk_radio_button_new_with_mnemonic (NULL, _("Sous-Terrain"));
  gtk_widget_show (RBSOUSTERRAIN_m);
  gtk_fixed_put (GTK_FIXED (fixed5), RBSOUSTERRAIN_m, 920, 408);
  gtk_widget_set_size_request (RBSOUSTERRAIN_m, 144, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RBSOUSTERRAIN_m), RBSOUSTERRAIN_m_group);
  RBSOUSTERRAIN_m_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RBSOUSTERRAIN_m));

  RBSURFACE_m = gtk_radio_button_new_with_mnemonic (NULL, _("Surface"));
  gtk_widget_show (RBSURFACE_m);
  gtk_fixed_put (GTK_FIXED (fixed5), RBSURFACE_m, 920, 440);
  gtk_widget_set_size_request (RBSURFACE_m, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RBSURFACE_m), RBSOUSTERRAIN_m_group);
  RBSOUSTERRAIN_m_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RBSURFACE_m));

  RBAERIEN_m = gtk_radio_button_new_with_mnemonic (NULL, _("A\303\251rien"));
  gtk_widget_show (RBAERIEN_m);
  gtk_fixed_put (GTK_FIXED (fixed5), RBAERIEN_m, 920, 472);
  gtk_widget_set_size_request (RBAERIEN_m, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RBAERIEN_m), RBSOUSTERRAIN_m_group);
  RBSOUSTERRAIN_m_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RBAERIEN_m));

  CBREGION_m = gtk_combo_box_new_text ();
  gtk_widget_show (CBREGION_m);
  gtk_fixed_put (GTK_FIXED (fixed5), CBREGION_m, 904, 272);
  gtk_widget_set_size_request (CBREGION_m, 224, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Centre_ville_Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Sidi_Bousaid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("El_Manzeh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Lac1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Lac2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Carthage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Centre_ville_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Zone_Indus_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Centre_Ville_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Zone_Indus_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Azur_City  "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Tunis_City "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Manar_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (CBREGION_m), _("Tunisia_Mall "));

  Ajouter_PARKY = gtk_button_new ();
  gtk_widget_show (Ajouter_PARKY);
  gtk_fixed_put (GTK_FIXED (fixed5), Ajouter_PARKY, 32, 584);
  gtk_widget_set_size_request (Ajouter_PARKY, 150, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (Ajouter_PARKY), alignment12);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox11);

  image20 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox11), image20, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox11), label41, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label41, 80, 30);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  label38 = gtk_label_new ("");
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 800, 592);
  gtk_widget_set_size_request (label38, 369, 41);

  afficher_fekher = gtk_button_new ();
  gtk_widget_show (afficher_fekher);
  gtk_fixed_put (GTK_FIXED (fixed5), afficher_fekher, 456, 584);
  gtk_widget_set_size_request (afficher_fekher, 150, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (afficher_fekher), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image18 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox9), image18, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox9), label39, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow1, 32, 240);
  gtk_widget_set_size_request (scrolledwindow1, 672, 304);

  treeview_parking = gtk_tree_view_new ();
  gtk_widget_show (treeview_parking);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_parking);
  gtk_widget_set_size_request (treeview_parking, 800, 300);

  label42 = gtk_label_new (_("<span color=\"navy Blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">Faire une Modification </span>"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed5), label42, 840, 152);
  gtk_widget_set_size_request (label42, 304, 48);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  label55 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Nom de parking</span>"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed5), label55, 752, 224);
  gtk_widget_set_size_request (label55, 160, 32);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  label54 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Region de parking</span>\n"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed5), label54, 744, 280);
  gtk_widget_set_size_request (label54, 160, 24);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  label53 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Capacit\303\251</span>\n"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed5), label53, 816, 328);
  gtk_widget_set_size_request (label53, 88, 16);
  gtk_label_set_use_markup (GTK_LABEL (label53), TRUE);

  label52 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Nombres de blocs</span>"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed5), label52, 736, 368);
  gtk_widget_set_size_request (label52, 168, 32);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  label51 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Type de parking</span>"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed5), label51, 752, 440);
  gtk_widget_set_size_request (label51, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  label56 = gtk_label_new (_("<span color=\"black\"font-weight=\"Bold\" font=\"georgia\" >Date d'ajout</span>"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed5), label56, 760, 520);
  gtk_widget_set_size_request (label56, 128, 24);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  image32 = create_pixmap (GestionParky, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed5), image32, 576, 8);
  gtk_widget_set_size_request (image32, 248, 208);

  label43 = gtk_label_new (_("<span color=\"navy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">Listes des Parkings </span>"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed5), label43, 160, 160);
  gtk_widget_set_size_request (label43, 392, 56);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  afficher_affect_agent = gtk_button_new ();
  gtk_widget_show (afficher_affect_agent);
  gtk_fixed_put (GTK_FIXED (fixed5), afficher_affect_agent, 648, 584);
  gtk_widget_set_size_request (afficher_affect_agent, 136, 40);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (afficher_affect_agent), alignment19);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox18);

  image33 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox18), image33, FALSE, FALSE, 0);

  label108 = gtk_label_new_with_mnemonic (_("Affecter"));
  gtk_widget_show (label108);
  gtk_box_pack_start (GTK_BOX (hbox18), label108, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) modifier_fekher, "clicked",
                    G_CALLBACK (on_modifier_fekher_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_fekher, "clicked",
                    G_CALLBACK (on_supprimer_fekher_clicked),
                    NULL);
  g_signal_connect ((gpointer) loop, "clicked",
                    G_CALLBACK (on_loop_clicked),
                    NULL);
  g_signal_connect ((gpointer) RBSOUSTERRAIN_m, "toggled",
                    G_CALLBACK (on_RBSOUSTERRAIN_m_toggled),
                    NULL);
  g_signal_connect ((gpointer) RBSURFACE_m, "toggled",
                    G_CALLBACK (on_RBSURFACE_m_toggled),
                    NULL);
  g_signal_connect ((gpointer) RBAERIEN_m, "toggled",
                    G_CALLBACK (on_RBAERIEN_m_toggled),
                    NULL);
  g_signal_connect ((gpointer) Ajouter_PARKY, "clicked",
                    G_CALLBACK (on_Ajouter_PARKY_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher_fekher, "clicked",
                    G_CALLBACK (on_afficher_fekher_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_parking, "row_activated",
                    G_CALLBACK (on_treeview_parking_row_activated),
                    NULL);
  g_signal_connect ((gpointer) afficher_affect_agent, "clicked",
                    G_CALLBACK (on_afficher_affect_agent_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionParky, GestionParky, "GestionParky");
  GLADE_HOOKUP_OBJECT (GestionParky, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (GestionParky, ERECHERCHE, "ERECHERCHE");
  GLADE_HOOKUP_OBJECT (GestionParky, ENOM_m, "ENOM_m");
  GLADE_HOOKUP_OBJECT (GestionParky, ECAPACITE_m, "ECAPACITE_m");
  GLADE_HOOKUP_OBJECT (GestionParky, SBBLOC_m, "SBBLOC_m");
  GLADE_HOOKUP_OBJECT (GestionParky, SBJJ_m, "SBJJ_m");
  GLADE_HOOKUP_OBJECT (GestionParky, SBMM_m, "SBMM_m");
  GLADE_HOOKUP_OBJECT (GestionParky, SBYYYY_m, "SBYYYY_m");
  GLADE_HOOKUP_OBJECT (GestionParky, modifier_fekher, "modifier_fekher");
  GLADE_HOOKUP_OBJECT (GestionParky, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (GestionParky, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (GestionParky, image25, "image25");
  GLADE_HOOKUP_OBJECT (GestionParky, label57, "label57");
  GLADE_HOOKUP_OBJECT (GestionParky, supprimer_fekher, "supprimer_fekher");
  GLADE_HOOKUP_OBJECT (GestionParky, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (GestionParky, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (GestionParky, image16, "image16");
  GLADE_HOOKUP_OBJECT (GestionParky, label36, "label36");
  GLADE_HOOKUP_OBJECT (GestionParky, loop, "loop");
  GLADE_HOOKUP_OBJECT (GestionParky, image15, "image15");
  GLADE_HOOKUP_OBJECT (GestionParky, RBSOUSTERRAIN_m, "RBSOUSTERRAIN_m");
  GLADE_HOOKUP_OBJECT (GestionParky, RBSURFACE_m, "RBSURFACE_m");
  GLADE_HOOKUP_OBJECT (GestionParky, RBAERIEN_m, "RBAERIEN_m");
  GLADE_HOOKUP_OBJECT (GestionParky, CBREGION_m, "CBREGION_m");
  GLADE_HOOKUP_OBJECT (GestionParky, Ajouter_PARKY, "Ajouter_PARKY");
  GLADE_HOOKUP_OBJECT (GestionParky, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (GestionParky, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (GestionParky, image20, "image20");
  GLADE_HOOKUP_OBJECT (GestionParky, label41, "label41");
  GLADE_HOOKUP_OBJECT (GestionParky, label38, "label38");
  GLADE_HOOKUP_OBJECT (GestionParky, afficher_fekher, "afficher_fekher");
  GLADE_HOOKUP_OBJECT (GestionParky, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (GestionParky, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (GestionParky, image18, "image18");
  GLADE_HOOKUP_OBJECT (GestionParky, label39, "label39");
  GLADE_HOOKUP_OBJECT (GestionParky, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (GestionParky, treeview_parking, "treeview_parking");
  GLADE_HOOKUP_OBJECT (GestionParky, label42, "label42");
  GLADE_HOOKUP_OBJECT (GestionParky, label55, "label55");
  GLADE_HOOKUP_OBJECT (GestionParky, label54, "label54");
  GLADE_HOOKUP_OBJECT (GestionParky, label53, "label53");
  GLADE_HOOKUP_OBJECT (GestionParky, label52, "label52");
  GLADE_HOOKUP_OBJECT (GestionParky, label51, "label51");
  GLADE_HOOKUP_OBJECT (GestionParky, label56, "label56");
  GLADE_HOOKUP_OBJECT (GestionParky, image32, "image32");
  GLADE_HOOKUP_OBJECT (GestionParky, label43, "label43");
  GLADE_HOOKUP_OBJECT (GestionParky, afficher_affect_agent, "afficher_affect_agent");
  GLADE_HOOKUP_OBJECT (GestionParky, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (GestionParky, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (GestionParky, image33, "image33");
  GLADE_HOOKUP_OBJECT (GestionParky, label108, "label108");

  return GestionParky;
}

