/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_menu_Admin (void);
GtkWidget* create_Modification (void);
GtkWidget* create_Menu_User (void);
GtkWidget* create_Ajouter_Reservation (void);
GtkWidget* create_Reservations_Listes (void);
GtkWidget* create_Ajout (void);
GtkWidget* create_affectation (void);
GtkWidget* create_GestionParky (void);
